name       : musl
version    : 1.1.19
release    : 4
source     :
    - https://www.musl-libc.org/releases/musl-1.1.19.tar.gz : db59a8578226b98373f5b27e61f0dd29ad2456f4aa9cec587ba8c24508e4c1d9
license    : MIT
component  : programming.library
summary    : MIT implementation of the C Standard Library
description: |
    musl, pronounced like the word "mussel", is an MIT-licensed
    implementation of the standard C library targetting the Linux syscall
    API, suitable for use in a wide range of deployment environments. musl
    offers efficient static and dynamic linking support, lightweight code
    and low runtime overhead, strong fail-safe guarantees under correct
    usage, and correctness in the sense of standards conformance and
    safety. musl is built on the principle that these goals are best
    achieved through simple code that is easy to understand and maintain.
libsplit   : no
patterns   :
    - devel : /usr/bin
setup      : |
    %apply_patches
    unset CXXFLAGS CFLAGS LDFLAGS
    export CFLAGS="-fPIC -pipe -g2 -mtune=generic -march=x86-64"

    export LANGUAGE="C"
    export LC_ALL="C"
    export LANG="C"

    ./configure --prefix=/usr \
                --bindir=/usr/bin \
                --includedir=/usr/include/musl \
                --libdir=%libdir%/musl \
                --enable-visibility \
                --enable-optimize=auto \
                --syslibdir=/lib64 \
                CC=$CC \
                CFLAGS=$CFLAGS
    # --syslibdir= /usr/lib64 /usr/lib32
build      : |
    %make
install    : |
    %make_install
