name       : musl
version    : 1.2.4
release    : 10
source     :
    - https://musl.libc.org/releases/musl-1.2.4.tar.gz : 7a35eae33d5372a7c0da1188de798726f68825513b7ae3ebe97aaaa52114f039
license    : MIT
component  : programming.library
homepage   : https://musl.libc.org/
summary    : MIT implementation of the C Standard Library
description: |
    musl, pronounced like the word "mussel", is an MIT-licensed implementation of the standard C library targetting the Linux syscall API, suitable for use in a wide range of deployment environments. musl offers efficient static and dynamic linking support, lightweight code and low runtime overhead, strong fail-safe guarantees under correct usage, and correctness in the sense of standards conformance and safety. musl is built on the principle that these goals are best achieved through simple code that is easy to understand and maintain.
libsplit   : no
patterns   :
    - devel : /usr/bin
setup      : |
    %apply_patches
    unset CXXFLAGS CFLAGS LDFLAGS
    export CFLAGS="-fPIC -pipe -g2 -mtune=generic -march=x86-64"

    export LANGUAGE="C"
    export LC_ALL="C"
    export LANG="C"

    ./configure --prefix=/usr \
                --bindir=/usr/bin \
                --includedir=/usr/include/musl \
                --libdir=%libdir%/musl \
                --enable-visibility \
                --enable-optimize=auto \
                --syslibdir=%libdir% \
                CC=$CC \
                CFLAGS=$CFLAGS
build      : |
    %make
install    : |
    %make_install
